name: Excel Maker V02

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev python3-pip ninja-build meson

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --no-build-isolation -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FTP_HOST_AC: ${{ secrets.FTP_HOST_AC }}
          FTP_USER_AC: ${{ secrets.FTP_USER_AC }}
          FTP_PASSWORD_AC: ${{ secrets.FTP_PASSWORD_AC }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
